### ISSUE TITLE
Got kicked for teleporting.

### ISSUE THREAD

**Issue by EGYbkgo9449** [rt-2/SA-ARP#13]
Hello,
I remember that I was just driving a car then I got kicked for teleporting...
I don't think I was going too fast tho...

**Comment by rt-2** [comment]
Do you remember what was the code given when you got kicked? (Usually a number like 002 or 023)
Thank you,
rt-2

**Comment by EGYbkgo9449** [comment]
Nope, sorry.

**Comment by rt-2** [comment]
Do you have any other information before I close this issue? Maybe where you were driving, did you drive there before that day, or anything else you think of?
Thank you,
rt-2

**Comment by EGYbkgo9449** [comment]
I don't think so.

**Comment by rt-2** [comment]
Alright, I will close this issue because no more investigation can be made at the moment, but it will stay in the archive and we may use it as reference in another issue.
rt-2
