### ISSUE TITLE
Got kicked for weapon hack.

### ISSUE THREAD

**Issue by EGYbkgo9449** [rt-2/SA-ARP#14]
Hello,
This one happened to me a lot, but when I try to re-create it, it doesn't happen, I got kicked for weapon hacking when I picked up the weapons/items from LSPD... some times I get kicked immediately after picking up the items, and sometimes I get kicked when I switch to another weapon while getting the items.

**Comment by rt-2** [comment]
Do you remember what was the code given when you got kicked? (Usually a number like 002 or 023)
Thank you,
rt-2

**Comment by EGYbkgo9449** [comment]
No, I don't.
Sorry.

**Comment by rt-2** [comment]
Do you have any other information before I close this topic. Maybe what you were doing before going to the PD, did you use guns before the LSPD ones, or anything else you think of?
Thank you,
rt-2

**Comment by EGYbkgo9449** [comment]
Nope, I've went straight to LSPD after joining the server.

**Comment by rt-2** [comment]
Alright thank you for the informstion, I will close this issue because no more investigation can be made at the moment, but it will stay in the archive and we may use it as reference in another issue.
rt-2
