### ISSUE TITLE
RP time scale to real time is not consistent

### ISSUE THREAD

**Issue by BananaBlooD9517** [rt-2/SA-ARP#518]
Rule 2 of Physic Rules make no sense at all. 

1 RP day = 1 OOC minute;
1 RP week = 1 OOC hour;
1 RP month = 1 OOC week;
1 RP year = 1 OOC month;

Following line 1, 7min IRL = 1week but it doesn't make sense at all. Line 2 state that 1RP week= 1h IRL which make the most sense as we get a paycheck every 1h IRL thus every week. Also 1 OOC week mean 168h which again doesn't equate the 1 RP week = 1 OOC hour.

In my opinion it should be changed to

1 RP week = 1 OOC hour
1 RP month = 4 RP weeks = 4 OOC hours
1 RP year =  52 RP weeks = 52h OOC hours

This is way more consistent with the 1 RP week = 1 OOC hour.

**Comment by rt-2** [comment]
The time setting is the same as most SAMP RP Server (flexible for RP purposes), `invalid`.

Changing this can break past RP. 
Especially because this is not an issue, just a possible enhancement. `wont fix`
