### ISSUE TITLE
No damage from bullets

### ISSUE THREAD

**Issue by BananaBlooD** [rt-2/sa-arp#7]
I had a fight with someone with only 9mm, we both shot at least 3-4 charger and we got little to no damage and headshot didn't seem to work.

**Comment by rt-2** [comment]
Unfortunately, there is very little information about the bug.
First of all, there is a high possibility that you just missed most of your bullets.
Also, most people argue that the damage on the 9mm is too low by default.
I think some real testing should be conducted about this.
If I'm not wrong @BananaBlooD you are in the testing faction, that could be a worthy test if you think something is not working at the moment.

**Comment by rt-2** [comment]
After investigation, I have found that ALL of damages done by guns we're deactivated because of an internal bug caused by the recent new tasks by ELC Anti-Cheat in 'OnPlayerWeaponShot'.
We will fix this issue very soon.

**Comment by rt-2** [comment]
This bug has been found and fixed.
