### ISSUE TITLE
Forklifts can be locked

### ISSUE THREAD

**Issue by rt-2** [rt-2/SA-ARP#73]
they shouldnt

**Comment by rt-2** [comment]
fixed, needs to be tested

**Comment by JamesCole1999** [comment]
test

**Comment by rt-2** [comment]
modification made, needs to be tested after 2020-06-01 restart

**Comment by rt-2** [comment]
everything works except using the 'SUBMISSION' key (É / 2)

**Comment by rt-2** [comment]
has been changed, needs to be tested

**Comment by rt-2** [comment]
Tested by James, fixed
