### ISSUE TITLE
Kicked for "Pro aim (ACV4: NA029)" when shooting sniper twice

### ISSUE THREAD

**Issue by rt-2** [rt-2/SA-ARP#84]

**Comment by rt-2** [comment]
cant reproduce

**Comment by rt-2** [comment]
Happened to Yanick on a Country Rifle
![image](https://user-images.githubusercontent.com/3452428/139588448-4b32eb40-bb7b-46ef-8464-dfaef4008fc8.png)

**Comment by rt-2** [comment]
Is not `important` because was not witnessed in the last 2-3 years

**Comment by puhnastiyus** [comment]
this doesn't happen, when i shoot with county rifle
i'll try limiting fps to 30

**Comment by puhnastiyus** [comment]
![sa-mp-306](https://user-images.githubusercontent.com/77493509/218085589-b804f05a-8c32-4937-9021-babf343074b2.png)
w/ 30 fps limit

**Comment by rt-2** [comment]
The original issue is here: https://github.com/NexiusTailer/Nex-AC/issues?q=is%3Aissue+pro+aim

All further informations must be send there.

I am `closing`
